### ISSUE TITLE
Undefined packet warning

### ISSUE THREAD

**Issue by ChiboYen** [Nan1t/NanoLimbo#12] opened 2021-12-29 21:07 UTC
I am getting this error on the console when a 1.18.1 client connects:
```
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0x11
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
[09:06:56] [WARNING]: Undefined incoming packet: 0xa
```
It keeps on spamming over and over, repeating for thousands of lines. I'm not sure if this is a big issue or if I can ignore it by setting the debug level to 0, just letting you know!

**Comment by Nan1t** [comment] 2021-12-30 16:24
Duplicate of #7 issue. This is not a bug. You need to set debug level to 0, as described in installation instruction.

**Closed by Nan1t** 2021-12-30 16:24 UTC
