### ISSUE TITLE
World support

### ISSUE THREAD

**Issue by zReport02** [Nan1t/NanoLimbo#10] opened 2021-12-23 01:49 UTC
Hi, I have a server with limbo and waterfall as a proxy!
I would like to have a mini lobby as a limbo server instead of the void!
It's possible?

**Comment by Nan1t** [comment] 2021-12-23 12:55
This possible in other limbo servers. NanoLimbo has no world support and won't. This requires more time to support server with world packets.

**Comment by Nan1t** [comment] 2022-01-12 10:04
Seems like this duplicate of #4, so i will close this issue. Recently i replied about this in original issue.

**Closed** 2022-01-12 10:05 UTC
Labels: duplicate
